### ISSUE TITLE
Local refinement l_new的取值范围

### ISSUE THREAD

**Issue by xiaoyaod** [veizgyauzgyauz/FCFI#3]
训练过程中 M_box 是基于最新添加的点 还是总过的点  M^r _t-1 是怎么来的

**Comment by veizgyauzgyauz** [comment]
1. l_{new}的取值范围为{0,1}，即0或1。
l_{new}∈{0,1}.

2. 训练过程中，M_{box}是一个与M^r_{t-1}尺寸一样（H’ x W’）的张量，其中在以最新添加的点为中心， rH’ x rW’大的矩形区域内的像素为1，其余像素为0，所以是基于最新添加的点。
During training, M_{box} is an H’ x W’ tensor, which has the same spatial size as M^r_{t-1}. In M_{box}, the pixels within the rH’ x rW’ rectangle region, centered on the new annotated click, are set to 1, while the pixels outside this region are set to 0. Therefore, M_{box} is constructed based on the latest annotated click.

3. 计算新添加点与其余点的特征相似性，然后通过公式2得到矫正后的反馈M^r’_ {t-1}，保留M^r’_ {t-1}中上述矩形区域的像素值，将矩形区域外的像素值替换为M_{t-1}中对应的像素值，可得到M^r_{t-1}，见公式(3)。
We calculate the feature similarities between the new annotated click and other pixels. By applying Eq. (2), we refine the feedback M_{t-1} to obtain the refined feedback M^r’_ {t-1}. We retain the pixel values within the rectangle region and replace the pixel values outside the region with their corresponding pixel values from M_{t-1}. Then we can obtain M^r_{t-1} (see Eq.(3)).
